# Certbot Auto-Renewal Setup
# This Docker Compose file orchestrates automated SSL/TLS certificate renewal,
# utilizing the Certbot image. Mapped volumes ensure configurations and
# challenges persist. The container employs a scripted entry point for renewal
# tasks and proper signal handling.
#
# Author: https://github.com/nerrad567/bookish-funicular
#
# Dependencies:
# - Docker 19.03.0+
# - Docker Compose '3'
# - Certbot Docker Image
# - Persistent storage access for configurations and challenges

version: "3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - /....certbot/conf:/etc/letsencrypt
      - /..../www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
